services:
  backend-perf:
    environment:
      POSTGRES_HOST: pgbouncer-perf
      POSTGRES_PORT: "6432"
      DB_POOL_SIZE: "2"
      DB_MAX_OVERFLOW: "0"
    depends_on:
      pgbouncer-perf:
        condition: service_started
